# FastAgent Configuration File

# Default Model Configuration:
#
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4.1, gpt-4.1-mini, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku".
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: haiku

# Logging and Console Configuration:
logger:
  level: "error" 
  type: "console" 
  # path: "/path/to/logfile.jsonl"

  # Switch the progress display on or off
  progress_display: true

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true

# MCP Servers
mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    hf:
      transport: "http"
      url: "https://hf.co/mcp"
    playwright:
       command: "npx"
       args: ["@playwright/mcp@latest"]
    # Elicitation test servers for different modes
    elicitation_forms_mode:
      command: "uv"
      args: ["run", "tests/integration/elicitation/elicitation_test_server_advanced.py"]
      transport: "stdio"
      cwd: "."
      elicitation:
        mode: "forms"
    
    elicitation_auto_cancel_mode:
      command: "uv"
      args: ["run", "tests/integration/elicitation/elicitation_test_server_advanced.py"]
      transport: "stdio"
      cwd: "."
      elicitation:
        mode: "auto_cancel"
    
    elicitation_none_mode:
      command: "uv"
      args: ["run", "tests/integration/elicitation/elicitation_test_server_advanced.py"]
      transport: "stdio"
      cwd: "."
      elicitation:
        mode: "none"
    
    elicitation_custom_handler:
      command: "uv"
      args: ["run", "tests/integration/elicitation/elicitation_test_server_advanced.py"]
      transport: "stdio"
      cwd: "."
      elicitation:
        mode: "forms"  # Will be overridden by custom handler
    
    # Legacy server names for backward compatibility
    elicitation_test:
      command: "python"
      args: ["tests/integration/elicitation/elicitation_test_server.py"]
    elicitation_test_advanced:
      command: "python"
      args: ["tests/integration/elicitation/elicitation_test_server_advanced.py"]
    elicit_advanced:
      command: "python"
      args: ["tests/integration/elicitation/elicitation_test_server_advanced.py"]
