# FastAgent configuration for Dynamic Agents example
#
# This configuration includes MCP servers that dynamic agents can use

app:
  log_dir: ".logs"

llm:
  default_model: "haiku"  # Fast model for demonstrations
  
mcp:
  defaults:
    auto_install_dependencies: true
    
  servers:
    # Filesystem server for file operations
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
        
    # Fetch server for web requests
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]