from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

import pytest

from fast_agent.plugins import operations as plugin_operations
from fast_agent.plugins.models import MarketplacePlugin
from fast_agent.plugins.operations import (
    apply_plugin_updates,
    check_plugin_updates,
    check_plugin_updates_in_roots,
    fetch_marketplace_plugins_with_source_sync,
    install_marketplace_plugin_sync,
    select_plugin_by_name_or_index,
    select_plugin_updates,
)
from fast_agent.plugins.provenance import (
    compute_plugin_content_fingerprint,
    read_installed_plugin_source,
)


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _init_repo(repo: Path) -> None:
    subprocess.run(["git", "init", str(repo)], check=True, capture_output=True, text=True)
    _git(repo, "config", "user.email", "tests@example.com")
    _git(repo, "config", "user.name", "Test User")


def _commit_all(repo: Path, message: str) -> str:
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", message)
    return _git(repo, "rev-parse", "HEAD")


def _marketplace_plugin(name: str, repo_path: str) -> MarketplacePlugin:
    return MarketplacePlugin(
        name=name,
        description=None,
        repo_url="https://github.com/example/plugins",
        repo_ref=None,
        repo_path=repo_path,
    )


def test_select_plugin_by_name_or_index_accepts_install_dir_name_alias() -> None:
    plugin = _marketplace_plugin("bundle-entry", "plugins/canonical/PLUGIN.YAML")

    assert select_plugin_by_name_or_index([plugin], "canonical") is plugin


def test_select_plugin_by_name_or_index_rejects_ambiguous_install_dir_name_alias() -> None:
    plugins = [
        _marketplace_plugin("first", "bundles/shared/plugin.yaml"),
        _marketplace_plugin("second", "other/shared/plugin.yaml"),
    ]

    assert select_plugin_by_name_or_index(plugins, "shared") is None


def test_check_plugin_updates_in_roots_uses_global_indices(tmp_path: Path) -> None:
    project_plugins = tmp_path / "project" / "plugins"
    global_plugins = tmp_path / "global" / "plugins"
    (project_plugins / "alpha").mkdir(parents=True)
    (global_plugins / "beta").mkdir(parents=True)

    updates = check_plugin_updates_in_roots(destination_roots=(project_plugins, global_plugins))

    assert [(update.index, update.name) for update in updates] == [
        (1, "alpha"),
        (2, "beta"),
    ]
    assert select_plugin_updates(updates[1:], "2") == [updates[1]]


def _write_plugin(repo: Path) -> None:
    plugin_dir = repo / "plugins" / "finder"
    plugin_dir.mkdir(parents=True, exist_ok=True)
    (plugin_dir / "plugin.yaml").write_text(
        "schema_version: 1\n"
        "name: finder\n"
        "description: Finder plugin\n"
        "commands:\n"
        "  find:\n"
        "    description: Find things\n"
        "    handler: ./commands.py:find\n",
        encoding="utf-8",
    )
    (plugin_dir / "commands.py").write_text(
        "async def find(ctx):\n    return 'found'\n",
        encoding="utf-8",
    )


def _write_marketplace(
    repo: Path,
    path: Path,
    *,
    repo_path: str = "plugins/finder",
) -> None:
    path.write_text(
        json.dumps(
            {
                "command_plugins": [
                    {
                        "name": "finder",
                        "repo_url": repo.as_posix(),
                        "repo_path": repo_path,
                    }
                ]
            }
        ),
        encoding="utf-8",
    )


def test_plugin_content_fingerprint_ignores_generated_bytecode(tmp_path: Path) -> None:
    plugin_dir = tmp_path / "finder"
    plugin_dir.mkdir()
    (plugin_dir / "plugin.yaml").write_text(
        "schema_version: 1\nname: finder\ncommands: {}\n",
        encoding="utf-8",
    )
    before = compute_plugin_content_fingerprint(plugin_dir)

    pycache = plugin_dir / "__pycache__"
    pycache.mkdir()
    (pycache / "commands.cpython-314.pyc").write_bytes(b"generated bytecode")

    assert compute_plugin_content_fingerprint(plugin_dir) == before


def test_plugin_update_ignores_unrelated_repo_commit_when_plugin_tree_same(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path)

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_dir = install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)
    read_result = read_installed_plugin_source(install_dir)
    assert read_result.error is None
    assert read_result.source is not None
    assert read_result.source.installed_path_oid is not None

    (repo / "README.md").write_text("unrelated change\n", encoding="utf-8")
    _commit_all(repo, "unrelated")

    updates = check_plugin_updates(destination_root=destination_root)

    assert len(updates) == 1
    assert updates[0].status == "up_to_date"
    assert updates[0].detail == "already up to date"


def test_plugin_install_from_manifest_path_tracks_whole_plugin_directory(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path, repo_path="plugins/finder/plugin.yaml")

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_dir = install_marketplace_plugin_sync(
        plugins[0],
        destination_root=destination_root,
    )

    read_result = read_installed_plugin_source(install_dir)
    assert read_result.error is None
    assert read_result.source is not None
    assert read_result.source.repo_path == "plugins/finder"
    assert read_result.source.installed_path_oid is not None

    (repo / "plugins" / "finder" / "commands.py").write_text(
        "async def find(ctx):\n    return 'updated'\n",
        encoding="utf-8",
    )
    _commit_all(repo, "update command")

    updates = check_plugin_updates(destination_root=destination_root)

    assert len(updates) == 1
    assert updates[0].status == "update_available"


def test_plugin_install_rejects_entry_name_that_escapes_managed_root(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    (repo / "plugin.yaml").write_text(
        "schema_version: 1\nname: finder\ndescription: Finder plugin\n",
        encoding="utf-8",
    )
    _commit_all(repo, "initial")

    # The plugin is the repo root, so the manifest's parent contributes no directory name
    # and install_dir_name falls back to the entry name, which the payload controls.
    marketplace_path = tmp_path / "marketplace.json"
    marketplace_path.write_text(
        json.dumps(
            {
                "command_plugins": [
                    {
                        "name": "../../escaped",
                        "repo_url": repo.as_posix(),
                        "repo_path": "plugin.yaml",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    assert [plugin.install_dir_name for plugin in plugins] == ["../../escaped"]

    destination_root = tmp_path / "managed" / "plugins"
    with pytest.raises(ValueError, match="not a single path component"):
        install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)

    assert not (tmp_path / "escaped").exists()
    assert list(destination_root.iterdir()) == []


def test_plugin_install_stages_inside_managed_root_for_hostile_entry_name(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")

    # install_dir_name comes from the repo path here, so the install itself is fine; the
    # staging directory was the second place the raw entry name reached the filesystem.
    # Three levels are needed rather than two: the prefix puts a "." before the name, and
    # ".." + ".." becomes the literal component "..." plus one climb, so "../../escaped"
    # still lands inside the root and would pass this test without exercising anything.
    marketplace_path = tmp_path / "marketplace.json"
    marketplace_path.write_text(
        json.dumps(
            {
                "command_plugins": [
                    {
                        "name": "../../../escaped",
                        "repo_url": repo.as_posix(),
                        "repo_path": "plugins/finder",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    assert plugins[0].name == "../../../escaped"
    assert plugins[0].install_dir_name == "finder"

    destination_root = tmp_path / "managed" / "plugins"
    staged_dirs: list[Path] = []
    real_temporary_directory = tempfile.TemporaryDirectory

    def _recording_temporary_directory(
        *,
        dir: Path,  # noqa: A002 - matches the tempfile keyword the caller uses
        prefix: str,
    ) -> "tempfile.TemporaryDirectory[str]":
        created = real_temporary_directory(dir=dir, prefix=prefix)
        staged_dirs.append(Path(created.name))
        return created

    monkeypatch.setattr(
        plugin_operations.tempfile,
        "TemporaryDirectory",
        _recording_temporary_directory,
    )
    install_dir = install_marketplace_plugin_sync(
        plugins[0],
        destination_root=destination_root,
    )

    assert install_dir == destination_root.resolve() / "finder"
    assert staged_dirs
    for staged in staged_dirs:
        assert staged.resolve().parent == destination_root.resolve()


def test_plugin_update_reports_missing_local_repo_ref(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path)

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_dir = install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)

    sidecar_path = install_dir / ".plugin-source.json"
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["repo_ref"] = "missing-ref"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")

    updates = check_plugin_updates(destination_root=destination_root)

    assert len(updates) == 1
    assert updates[0].status == "source_ref_missing"
    assert updates[0].detail == "ref not found: missing-ref"


def test_plugin_update_reports_missing_local_source_path(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    _write_plugin(repo)
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path)

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)

    (repo / "plugins" / "finder" / "plugin.yaml").unlink()

    updates = check_plugin_updates(destination_root=destination_root)

    assert len(updates) == 1
    assert updates[0].status == "source_path_missing"
    assert updates[0].detail == "Plugin manifest not found in repository: plugins/finder"


def test_apply_plugin_update_refreshes_stale_source_state(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path)

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_dir = install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)

    (repo / "plugins" / "finder" / "commands.py").write_text(
        "async def find(ctx):\n    return 'updated'\n",
        encoding="utf-8",
    )
    _commit_all(repo, "update plugin")
    stale_updates = check_plugin_updates(destination_root=destination_root)
    assert stale_updates[0].status == "update_available"

    _git(repo, "rm", "-r", "plugins/finder")
    _commit_all(repo, "remove plugin")

    applied = apply_plugin_updates(stale_updates, force=False)

    assert applied[0].status == "source_path_missing"
    assert applied[0].detail is not None
    assert "plugins/finder" in applied[0].detail
    assert install_dir.is_dir()
