# ruff: noqa: F821
"""Vulture allowlist for intentional dynamic and protocol-facing names.

These names are not dead implementation variables. They are retained because
they are part of public call signatures, Protocol definitions, or third-party
callback contracts where keyword names matter.
"""

call_index
current_total
exist_ok
password
path_or_fileobj
pretty_print_parallel
recursive
repo_type

# Schema/dataclass payload fields where names are externally observed.
agents_as_tools_options
ASK
audio
carrier
codexresponses
commit_id
connect_at
country
customizationsSupported
customer_tier
destination_city
eta_days
execution_engine
final_json_valid
fulfillment
in_reply_to_id
inferenceTypesSupported
inputModalities
instructions_included
last_message_at
line_items
matched_direct_payload
matched_tool_payload
max_queue_size
mode_counts
modelId
modelLifecycle
modelName
on_shutdown
on_start
outputModalities
ping_last_at
plugins_recommended
provider_diagnostics
providerName
quantity
ready_to_ship
refusal
responseStreamingSupported
risk_flags
roots_count
skip_reason
sku
statuses
timing_summary
tool_calls
total_usd
transport_diagnostics
unit_price_usd
WARN
xai

# Public ACP convenience API. These are intentionally exposed for agents and
# examples even when not referenced by core runtime code.
_.acp_available_modes
_.acp_current_mode
_.acp_filesystem_runtime
_.acp_permission_handler
_.acp_progress_manager
_.acp_session_id
_.acp_supports_filesystem
_.acp_supports_fs_read
_.acp_supports_fs_write
_.acp_supports_terminal
_.acp_switch_mode
_.acp_terminal_runtime
_.enable_shell
_.is_acp_mode
_.use_context
is_acp
is_tui
mark_user_adjusted

# Protocol and file-like callback surfaces.
_.__getattr__
_.__signature__
_.do_GET
_.get_client_info
_.get_tokens
_.on_signal
_.upload_file
_.list_commands
_.process_renderables
_.readable
_.seekable
_.set_tokens
CompleterMcpAgent
CompleterResourceAgent
CompleterResourceArgumentCompletion
CompleterResourceMcpAgent
propose_new_texts

# Decorator-registered runtime callbacks.
batch_worker
default_fallback_agent
model_agent
setup_agent

# Typer command callbacks.
_demo_root
cards_add
cards_list
cards_main
cards_publish
cards_readme
cards_remove
cards_update
codex_clear
codex_login
codexplan
config_display
config_main
config_shell
data_analysis
login
model_doctor
model_export
model_llamacpp
model_llamacpp_import
model_llamacpp_list
model_llamacpp_preview
model_main
model_presets
model_setup
plugins_add
plugins_list
plugins_main
plugins_remove
plugins_update
researcher
run_acp
serve_a2a
skills_add
skills_available
skills_list
skills_main
skills_remove
skills_search
skills_update
state_transfer
toad_cards
workflow

# Pydantic validators.
_coerce_apply_patch_preview_max_lines
_coerce_max_missed_pings
_coerce_output_display_lines
_coerce_steps
_coerce_task_budget
_coerce_timeout
_coerce_warning_interval
_coerce_write_text_file_mode
_ignore_bool_context_length
_ignore_bool_limits
_normalize_access_token
_normalize_connector_id
_normalize_entry
_normalize_json_mode
_normalize_management_specific_settings
_normalize_optional_text
_normalize_payload
_normalize_server_targets
_reject_bool_integer_controls
_reject_bool_max_content_tokens
_reject_bool_max_uses
_reject_bool_number_controls
_reject_bool_numeric_values
_reject_bool_redirect_port
_reject_bool_sample_rate
_reject_bool_timeout_value
_snapshot_raw_usage
_validate_allowed_domains
_validate_auth_configuration
_validate_client_metadata_url
_validate_domains
_validate_domain_filters
_validate_excluded_domains
_validate_image_size
_validate_max_concurrent_activities
_validate_max_uses
_validate_model_alias_tokens
_validate_model_references
_validate_name
_validate_plugin_commands
_validate_positive_limits
_validate_timeout_seconds
_validate_uri
_validate_xai_allowed_domains
validate_role
validate_uri
validate_transport_inference

# MCP SDK transport override hooks.
_handle_json_response
_handle_resumption_request
_handle_sse_response

# Model factory registrations imported dynamically by provider key.
AliyunLLM
SilentLLM
SlowLLM

# Public model metadata helpers retained as API surface.
_.get_cache_ttl
_.get_json_mode

# FastMCP route/resource callbacks registered by decorator.
get_file_resource
root_info

# Prompt-toolkit keybinding callbacks registered by decorator.
focus_next_arrow
focus_next_right
focus_next_with_refresh
focus_previous_arrow
focus_previous_left
focus_previous_with_refresh
insert_newline_cj
insert_newline_enter
_remove
submit_enter
toggle_text_navigation_mode

# Attributes owned by third-party objects or test frameworks.
_.intra_op_num_threads
_.linkname
_.log_severity_level
_.no_wrap
_.preserve_quotes
_.should_exit
_.whitespace_split
_._height
occurred_at
pytestmark

# Test-only framework surfaces: pytest fixtures and FastMCP/FastAPI/agent
# decorator callbacks used by integration/e2e test servers.
CELSIUS
CLOUDY
FAHRENHEIT
RAINY
SNOWY
STORMY
SUNNY
async_double
bad_custom
calculate_divide
calculate_product
calculate_sum
check_weather
check_weather_prompt
chdir_to_tensorzero_example
cleanup_event_bus
cleanup_logging
clear_hook_calls
client_capabilities_resource
complete_resource_template_argument
_capture_transport_logger
debug_cache_at_end
delete_mcp
double
dummy_agent_func
dummy_simple_agent_func
dummy_tool
ext_method
ext_notification
foo_only
generate_short_story
get_both_data
get_hook_calls
get_image
get_mcp
get_page_data
get_pdf
get_video_link
getlink
get_status
greet
insert_newline_cj
insert_newline_enter
invalid_widget_resource
isolated
isolated_custom
isolate_environment_dir
isolate_fast_agent_environment
logprobs
math_add
math_constants
math_formulas
math_helper_prompt
math_multiply
math_subtract
math_teacher_prompt
_mock_hf_token_verifier
orphan_widget_resource
post_mcp
progress_task
progress_task_no_message
progress_task_with_helper
random_number
render_invalid_widget
render_missing_widget
render_valid_widget
restore_fast_agent_import_state
sample_many
sample_parallel
sample_with_image
set_cwd
shirt_colour
show_roots
simple_rating
smart_item
smart_static
string_examples
string_lower
string_processor_prompt
string_upper
take_screenshot
tensorzero_docker_env
text_reverse
text_uppercase
tool_a
tool_b
track_after_turn_complete
url_required_malformed_tool
url_required_valid_tool
user_profile
utility_assistant_prompt
utility_info
utility_ping
utility_status
valid_widget_resource
worker1
worker2
