"""Tests for binary resource saver functionality."""

import base64

from mcp.types import BlobResourceContents, EmbeddedResource, ImageContent
from pydantic import AnyUrl

from fast_agent.mcp.binary_resource_saver import (
    get_file_extension,
    save_binary_resource,
    save_mcp_content_blocks,
)


class TestGetFileExtension:
    """Tests for get_file_extension function."""

    def test_image_extensions(self):
        """Test that common image MIME types map to correct extensions."""
        assert get_file_extension("image/jpeg") == ".jpg"
        assert get_file_extension("image/jpg") == ".jpg"
        assert get_file_extension("image/png") == ".png"
        assert get_file_extension("image/gif") == ".gif"
        assert get_file_extension("image/webp") == ".webp"
        assert get_file_extension("image/svg+xml") == ".svg"

    def test_audio_extensions(self):
        """Test that common audio MIME types map to correct extensions."""
        assert get_file_extension("audio/mpeg") == ".mp3"
        assert get_file_extension("audio/wav") == ".wav"
        assert get_file_extension("audio/ogg") == ".ogg"

    def test_video_extensions(self):
        """Test that common video MIME types map to correct extensions."""
        assert get_file_extension("video/mp4") == ".mp4"
        assert get_file_extension("video/quicktime") == ".mov"
        assert get_file_extension("video/webm") == ".webm"

    def test_document_extensions(self):
        """Test that document MIME types map to correct extensions."""
        assert get_file_extension("application/pdf") == ".pdf"
        assert get_file_extension("application/zip") == ".zip"

    def test_unknown_mime_type_defaults_to_bin(self):
        """Test that unknown MIME types default to .bin extension."""
        assert get_file_extension("application/x-unknown") == ".bin"
        assert get_file_extension("") == ".bin"


class TestSaveBinaryResource:
    """Tests for save_binary_resource function."""

    def test_save_image_content(self, tmp_path):
        """Test saving an ImageContent block."""
        # Create test data (1x1 red pixel PNG)
        png_data = (
            b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00"
            b"\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\tpHYs\x00\x00"
            b"\x0b\x13\x00\x00\x0b\x13\x01\x00\x9a\x9c\x18\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82"
        )
        base64_data = base64.b64encode(png_data).decode("ascii")

        image_content = ImageContent(type="image", data=base64_data, mimeType="image/png")

        saved_path = save_binary_resource(
            content=image_content,
            output_dir=tmp_path,
            filename="test_image",
        )

        assert saved_path is not None
        assert saved_path.exists()
        assert saved_path.suffix == ".png"
        assert saved_path.name == "test_image.png"

        # Verify content
        saved_data = saved_path.read_bytes()
        assert saved_data == png_data

    def test_save_blob_resource_contents(self, tmp_path):
        """Test saving a BlobResourceContents block."""
        # Create test PDF data
        pdf_data = b"%PDF-1.4 test PDF content"
        base64_data = base64.b64encode(pdf_data).decode("ascii")

        blob_content = BlobResourceContents(
            uri=AnyUrl("file://test.pdf"),
            blob=base64_data,
            mimeType="application/pdf",
        )

        saved_path = save_binary_resource(
            content=blob_content,
            output_dir=tmp_path,
            filename="test_doc",
        )

        assert saved_path is not None
        assert saved_path.exists()
        assert saved_path.suffix == ".pdf"
        assert saved_path.name == "test_doc.pdf"

        # Verify content
        saved_data = saved_path.read_bytes()
        assert saved_data == pdf_data

    def test_autogenerate_filename(self, tmp_path):
        """Test that filenames are autogenerated when not provided."""
        image_data = base64.b64encode(b"fake image data").decode("ascii")
        image_content = ImageContent(type="image", data=image_data, mimeType="image/jpeg")

        saved_path = save_binary_resource(
            content=image_content,
            output_dir=tmp_path,
            filename=None,  # Auto-generate
        )

        assert saved_path is not None
        assert saved_path.exists()
        assert saved_path.suffix == ".jpg"
        # Should have format: image_YYYYMMDD_HHMMSS_xxxxxxxx.jpg
        assert saved_path.name.startswith("image_")
        assert len(saved_path.name) > 20  # Should be reasonably long

    def test_create_output_directory(self, tmp_path):
        """Test that output directory is created if it doesn't exist."""
        nested_dir = tmp_path / "nested" / "deep" / "directory"
        assert not nested_dir.exists()

        image_data = base64.b64encode(b"fake data").decode("ascii")
        image_content = ImageContent(type="image", data=image_data, mimeType="image/png")

        saved_path = save_binary_resource(
            content=image_content,
            output_dir=nested_dir,
            filename="test",
        )

        assert saved_path is not None
        assert nested_dir.exists()
        assert saved_path.exists()

    def test_return_none_on_failure(self, tmp_path):
        """Test that None is returned on failure."""
        # Create invalid base64 data
        image_content = ImageContent(type="image", data="invalid-base64!@#", mimeType="image/png")

        saved_path = save_binary_resource(
            content=image_content,
            output_dir=tmp_path,
            filename="test",
        )

        assert saved_path is None


class TestSaveMcpContentBlocks:
    """Tests for save_mcp_content_blocks function."""

    def test_save_multiple_content_types(self, tmp_path):
        """Test saving multiple different content types."""
        content_blocks = [
            ImageContent(
                type="image",
                data=base64.b64encode(b"image1").decode("ascii"),
                mimeType="image/png",
            ),
            ImageContent(
                type="image",
                data=base64.b64encode(b"image2").decode("ascii"),
                mimeType="image/jpeg",
            ),
            EmbeddedResource(
                type="resource",
                resource=BlobResourceContents(
                    uri=AnyUrl("file://test.mp3"),
                    blob=base64.b64encode(b"audio data").decode("ascii"),
                    mimeType="audio/mpeg",
                ),
            ),
            EmbeddedResource(
                type="resource",
                resource=BlobResourceContents(
                    uri=AnyUrl("file://test.pdf"),
                    blob=base64.b64encode(b"PDF content").decode("ascii"),
                    mimeType="application/pdf",
                ),
            ),
        ]

        saved_files = save_mcp_content_blocks(
            content_blocks=content_blocks,
            output_dir=tmp_path,
            save_images=True,
            save_audio=True,
            save_video=True,
            save_other_binaries=True,
        )

        assert len(saved_files) == 4

        # Check that files were created in appropriate subdirectories
        image_files = [f for f in saved_files if f.parent.name == "images"]
        audio_files = [f for f in saved_files if f.parent.name == "audio"]
        resource_files = [f for f in saved_files if f.parent.name == "resources"]

        assert len(image_files) == 2
        assert len(audio_files) == 1
        assert len(resource_files) == 1

    def test_selective_saving(self, tmp_path):
        """Test that selective saving works correctly."""
        content_blocks = [
            ImageContent(
                type="image",
                data=base64.b64encode(b"image data").decode("ascii"),
                mimeType="image/png",
            ),
            EmbeddedResource(
                type="resource",
                resource=BlobResourceContents(
                    uri=AnyUrl("file://test.mp3"),
                    blob=base64.b64encode(b"audio data").decode("ascii"),
                    mimeType="audio/mpeg",
                ),
            ),
        ]

        # Save only images, not audio
        saved_files = save_mcp_content_blocks(
            content_blocks=content_blocks,
            output_dir=tmp_path,
            save_images=True,
            save_audio=False,
            save_video=False,
            save_other_binaries=False,
        )

        assert len(saved_files) == 1
        assert saved_files[0].parent.name == "images"

    def test_skip_non_binary_content(self, tmp_path):
        """Test that non-binary content is skipped."""
        from mcp.types import TextContent

        content_blocks = [
            TextContent(type="text", text="Some text content"),
            ImageContent(
                type="image",
                data=base64.b64encode(b"image data").decode("ascii"),
                mimeType="image/png",
            ),
        ]

        saved_files = save_mcp_content_blocks(
            content_blocks=content_blocks,
            output_dir=tmp_path,
            save_images=True,
            save_audio=True,
            save_video=True,
            save_other_binaries=True,
        )

        # Only the image should be saved, not the text
        assert len(saved_files) == 1
        assert saved_files[0].suffix == ".png"

    def test_empty_content_blocks(self, tmp_path):
        """Test handling of empty content blocks list."""
        saved_files = save_mcp_content_blocks(
            content_blocks=[],
            output_dir=tmp_path,
        )

        assert len(saved_files) == 0

    def test_all_disabled_saving_options(self, tmp_path):
        """Test that no files are saved when all options are disabled."""
        content_blocks = [
            ImageContent(
                type="image",
                data=base64.b64encode(b"image data").decode("ascii"),
                mimeType="image/png",
            ),
            EmbeddedResource(
                type="resource",
                resource=BlobResourceContents(
                    uri=AnyUrl("file://test.mp3"),
                    blob=base64.b64encode(b"audio data").decode("ascii"),
                    mimeType="audio/mpeg",
                ),
            ),
        ]

        saved_files = save_mcp_content_blocks(
            content_blocks=content_blocks,
            output_dir=tmp_path,
            save_images=False,
            save_audio=False,
            save_video=False,
            save_other_binaries=False,
        )

        assert len(saved_files) == 0
