# Model string takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
#
# Can be overriden with a command line switch --model=<model>, or within the Agent decorator.
# Check here for current details: https://fast-agent.ai/models/
# default_model: "haiku"

# Logging and Console Configuration
logger:
  level: "error"
  type: "console"

# MCP Server Configuration
mcp:
  servers:
    # Main elicitation server with forms mode (for passthrough examples)
    elicitation_forms_server:
      command: "uv"
      args: ["run", "elicitation_forms_server.py"]
      elicitation:
        mode: "forms" # Can be "none", "auto_cancel" or "forms" (default: "forms").
